services:
  firestore:
    build:
      dockerfile: ./docker/firestore/Dockerfile.test.firestore
      args:
        - GO_BASE_IMAGE=${GO_BASE_IMAGE}
        - GOPROXY=${GOPROXY}
    container_name: firestore-dev
    env_file:
      - .env
      - .env.gcf
    networks:
      echart-backend_devcontainer_default:
        aliases:
          - ${FIRESTORE_EMULATOR_HOSTNAME}

  fake-gcs-server:
    image: fsouza/fake-gcs-server:latest
    container_name: fake-gcs-server-dev
    entrypoint: "fake-gcs-server -scheme http -port 4443 -public-host localhost"
    networks:
      echart-backend_devcontainer_default:
        aliases:
          - ${GCS_EMULATOR_HOSTNAME}

  gcf-emulator:
    build:
      dockerfile: ./docker/Dockerfile.gcf.mock
      args:
        - GO_BASE_IMAGE=${GO_BASE_IMAGE}
        - GOPROXY=${GOPROXY}
    env_file:
      - .env.gcf
      - .env
    environment:
      - FUNCTION_TARGET=AddEvent
    networks:
      echart-backend_devcontainer_default:
        aliases:
          - ${GCF_EMULATOR_HOSTNAME}
  rest-api:
    build:
      dockerfile: ./docker/rest-api/Dockerfile.rest.api
      args:
        - GO_BASE_IMAGE=${GO_BASE_IMAGE}
        - NODE_BASE_IMAGE=${NODE_BASE_IMAGE}
        - GOPROXY=${GOPROXY}
      target: ${REST_API_TARGET-production}
    env_file:
      - .env
      - .env.gcf
    networks:
      echart-backend_devcontainer_default:
        aliases:
          - ${API_EMULATOR_HOSTNAME}

networks:
  echart-backend_devcontainer_default:
    external: true
